// <auto-generated />
using System;
using EmployeeManagementChallenge.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmployeeManagementChallenge.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("EmployeeManagementChallenge.DAL.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Firstname")
                        .HasColumnType("longtext");

                    b.Property<string>("Lastname")
                        .HasColumnType("longtext");

                    b.Property<string>("Skills")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Firstname = "John",
                            Lastname = "Doe",
                            Skills = "1,2"
                        },
                        new
                        {
                            Id = 2,
                            Firstname = "Alice",
                            Lastname = "W"
                        },
                        new
                        {
                            Id = 3,
                            Firstname = "Ross",
                            Lastname = "Bob",
                            Skills = "2,3"
                        },
                        new
                        {
                            Id = 4,
                            Firstname = "Rachel",
                            Lastname = "Green",
                            Skills = "5"
                        });
                });

            modelBuilder.Entity("EmployeeManagementChallenge.DAL.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Details")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Details = "Knowledge of Python language",
                            Name = "Python",
                            TimeCreated = new DateTime(2023, 11, 30, 14, 57, 30, 631, DateTimeKind.Local).AddTicks(693)
                        },
                        new
                        {
                            Id = 2,
                            Details = "Knowledge of Java programming language",
                            Name = "Java",
                            TimeCreated = new DateTime(2023, 11, 30, 14, 57, 30, 632, DateTimeKind.Local).AddTicks(4159)
                        },
                        new
                        {
                            Id = 3,
                            Details = "Web Pages",
                            Name = "HTML",
                            TimeCreated = new DateTime(2023, 11, 30, 14, 57, 30, 632, DateTimeKind.Local).AddTicks(4172)
                        },
                        new
                        {
                            Id = 4,
                            Details = "Styling",
                            Name = "CSS",
                            TimeCreated = new DateTime(2023, 11, 30, 14, 57, 30, 632, DateTimeKind.Local).AddTicks(4173)
                        },
                        new
                        {
                            Id = 5,
                            Details = "DOM Handling",
                            Name = "JavaScript",
                            TimeCreated = new DateTime(2023, 11, 30, 14, 57, 30, 632, DateTimeKind.Local).AddTicks(4174)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
